apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ashishrajazurevotingappredis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ashishrajazurevotingappredis 
    spec:
      containers:
        - name: ashishrajazurevotingappredis 
          image: rlincregistry.azurecr.io/ashishrajazurevotingappredis
          ports:
          - containerPort: 80